/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#0B1120",
        "surface-dim": "#080E1A",
        "surface-bright": "#1E293B",
        "surface-container-lowest": "#050914",
        "surface-container-low": "#0F172A",
        "surface-container": "#111827",
        "surface-container-high": "#1E293B",
        "surface-container-highest": "#334155",
        "on-surface": "#F8FAFC",
        "on-surface-variant": "#94A3B8",
        "inverse-surface": "#F8FAFC",
        "inverse-on-surface": "#0F172A",
        "outline": "#475569",
        "outline-variant": "#1E293B",
        "surface-tint": "#06B6D4",
        "primary": "#2563EB",
        "on-primary": "#FFFFFF",
        "primary-container": "#2563EB",
        "on-primary-container": "#F8FAFC",
        "inverse-primary": "#3B82F6",
        "secondary": "#06B6D4",
        "on-secondary": "#0B1120",
        "secondary-container": "#0891B2",
        "on-secondary-container": "#ECFEFF",
        "tertiary": "#06B6D4",
        "on-tertiary": "#0B1120",
        "tertiary-container": "#06B6D4",
        "on-tertiary-container": "#F8FAFC",
        "error": "#EF4444",
        "on-error": "#FFFFFF",
        "error-container": "#7F1D1D",
        "on-error-container": "#FEE2E2",
        "background": "#0B1120",
        "on-background": "#F8FAFC",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "gutter": "1rem",
        "gutter-sm": "0.75rem",
        "gutter-lg": "1.5rem",
        "margin": "1.5rem",
        "margin-sm": "1rem",
        "margin-lg": "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "geist": ["Geist", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      }
    },
  },
  plugins: [],
}
