/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#031427",
        "surface-dim": "#031427",
        "surface-bright": "#2a3a4f",
        "surface-container-lowest": "#000f21",
        "surface-container-low": "#0b1c30",
        "surface-container": "#102034",
        "surface-container-high": "#1b2b3f",
        "surface-container-highest": "#26364a",
        "on-surface": "#d3e4fe",
        "on-surface-variant": "#b9cacb",
        "inverse-surface": "#d3e4fe",
        "inverse-on-surface": "#213145",
        "outline": "#849495",
        "outline-variant": "#3b494b",
        "surface-tint": "#00dbe9",
        "primary": "#dbfcff",
        "on-primary": "#00363a",
        "primary-container": "#00f0ff",
        "on-primary-container": "#006970",
        "inverse-primary": "#006970",
        "secondary": "#c0c1ff",
        "on-secondary": "#1000a9",
        "secondary-container": "#3131c0",
        "on-secondary-container": "#b0b2ff",
        "tertiary": "#d8ffe7",
        "on-tertiary": "#003824",
        "tertiary-container": "#65f2b5",
        "on-tertiary-container": "#006d4a",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "background": "#031427",
        "on-background": "#d3e4fe",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
      spacing: {
        "gutter": "1rem",
        "gutter-sm": "0.75rem",
        "gutter-lg": "1.5rem",
        "margin": "1.5rem",
        "margin-sm": "1rem",
        "margin-lg": "2rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "geist": ["Geist", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"],
      }
    },
  },
  plugins: [],
}
